import loadVideo from "./modules/loadVideo";
import "./styles.css";
import "./masonry.css";
import dropdown from "./modules/dropdown";
import countdown from "./modules/countdown";
import noDoubleTap from "./modules/noDoubleTap";
import sound from "./modules/sound";
import volumeControl from "./modules/volumeControl";
import home from "./modules/home";
import ourStory from "./modules/ourStory";
import translate from "./modules/translate";
import lightBox from "./modules/lightbox";

translate();
noDoubleTap();
home();
dropdown();
sound();
volumeControl();
countdown();
ourStory();
loadVideo();
lightBox();
